<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\State;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        State::truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $states = [
            ['name' => 'Andaman and Nicobar Islands', 'country_id' => 3],
            ['name' => 'Andhra Pradesh', 'country_id' => 3],
            ['name' => 'Arunachal Pradesh', 'country_id' => 3],
            ['name' => 'Assam', 'country_id' => 3],
            ['name' => 'Bihar', 'country_id' => 3],
            ['name' => 'Chandigarh', 'country_id' => 3],
            ['name' => 'Chhattisgarh', 'country_id' => 3],
            ['name' => 'Dadra and Nagar Haveli', 'country_id' => 3],
            ['name' => 'Daman and Diu', 'country_id' => 3],
            ['name' => 'Delhi', 'country_id' => 3],
            ['name' => 'Goa', 'country_id' => 3],
            ['name' => 'Gujarat', 'country_id' => 3],
            ['name' => 'Haryana', 'country_id' => 3],
            ['name' => 'Himachal Pradesh', 'country_id' => 3],
            ['name' => 'Jammu and Kashmir', 'country_id' => 3],
            ['name' => 'Jharkhand', 'country_id' => 3],
            ['name' => 'Karnataka', 'country_id' => 3],
            ['name' => 'Kerala', 'country_id' => 3],
            ['name' => 'Lakshadweep', 'country_id' => 3],
            ['name' => 'Madhya Pradesh', 'country_id' => 3],
            ['name' => 'Maharashtra', 'country_id' => 3],
            ['name' => 'Manipur', 'country_id' => 3],
            ['name' => 'Meghalaya', 'country_id' => 3],
            ['name' => 'Mizoram', 'country_id' => 3],
            ['name' => 'Nagaland', 'country_id' => 3],
            ['name' => 'Odisha', 'country_id' => 3],
            ['name' => 'Pondicherry', 'country_id' => 3],
            ['name' => 'Punjab', 'country_id' => 3],
            ['name' => 'Rajasthan', 'country_id' => 3],
            ['name' => 'Sikkim', 'country_id' => 3],
            ['name' => 'Tamil Nadu', 'country_id' => 3],
            ['name' => 'Telangana', 'country_id' => 3],
            ['name' => 'Tripura', 'country_id' => 3],
            ['name' => 'Uttar Pradesh', 'country_id' => 3],
            ['name' => 'Uttarakhand', 'country_id' => 3],
            ['name' => 'West Bengal', 'country_id' => 3],

            ['name' => 'Australian Capital Territory', 'country_id' => 1],
            ['name' => 'Balgowlah', 'country_id' => 1],
            ['name' => 'Balmain', 'country_id' => 1],
            ['name' => 'Bankstown', 'country_id' => 1],
            ['name' => 'Baulkham Hills', 'country_id' => 1],
            ['name' => 'Bonnet Bay', 'country_id' => 1],
            ['name' => 'Camberwell', 'country_id' => 1],
            ['name' => 'Carole Park', 'country_id' => 1],
            ['name' => 'Castle Hill', 'country_id' => 1],
            ['name' => 'Caulfield', 'country_id' => 1],
            ['name' => 'Chatswood', 'country_id' => 1],
            ['name' => 'Cheltenham', 'country_id' => 1],
            ['name' => 'Cherrybrook', 'country_id' => 1],
            ['name' => 'Clayton', 'country_id' => 1],
            ['name' => 'Collingwood', 'country_id' => 1],
            ['name' => 'Frenchs Forest', 'country_id' => 1],
            ['name' => 'Hawthorn', 'country_id' => 1],
            ['name' => 'Jannnali', 'country_id' => 1],
            ['name' => 'Knoxfield', 'country_id' => 1],
            ['name' => 'Melbourne', 'country_id' => 1],
            ['name' => 'New South Wales', 'country_id' => 1],
            ['name' => 'Northern Territory', 'country_id' => 1],
            ['name' => 'Perth', 'country_id' => 1],
            ['name' => 'Queensland', 'country_id' => 1],
            ['name' => 'South Australia', 'country_id' => 1],
            ['name' => 'Tasmania', 'country_id' => 1],
            ['name' => 'Templestowe', 'country_id' => 1],
            ['name' => 'Victoria', 'country_id' => 1],
            ['name' => 'Werribee south', 'country_id' => 1],
            ['name' => 'Western Australia', 'country_id' => 1],
            ['name' => 'Wheeler', 'country_id' => 1],

            ['name'=> 'Alberta','country_id'=> 2],
            ['name'=> 'British Columbia','country_id'=> 2],
            ['name'=> 'Manitoba','country_id'=> 2],
            ['name'=> 'New Brunswick','country_id'=> 2],
            ['name'=> 'Newfoundland and Labrador','country_id'=> 2],
            ['name'=> 'Northwest Territories','country_id'=> 2],
            ['name'=> 'Nova Scotia','country_id'=> 2],
            ['name'=> 'Nunavut','country_id'=> 2],
            ['name'=> 'Ontario','country_id'=> 2],
            ['name'=> 'Prince Edward Island','country_id'=> 2],
            ['name'=> 'Quebec','country_id'=> 2],
            ['name'=> 'Saskatchewan','country_id'=> 2],
            ['name'=> 'Yukon','country_id'=> 2],

            ['name'=> 'Area Outside Region','country_id'=> 4],
            ['name'=> 'Auckland','country_id'=> 4],
            ['name'=> 'Bay of Plenty','country_id'=> 4],
            ['name'=> 'Canterbury','country_id'=> 4],
            ['name'=> 'Christchurch','country_id'=> 4],
            ['name'=> 'Gisborne','country_id'=> 4],
            ['name'=> 'Hawkes Bay','country_id'=> 4],
            ['name'=> 'Manawatu-Wanganui','country_id'=> 4],
            ['name'=> 'Marlborough','country_id'=> 4],
            ['name'=> 'Nelson','country_id'=> 4],
            ['name'=> 'Northland','country_id'=> 4],
            ['name'=> 'Otago','country_id'=> 4],
            ['name'=> 'Rodney','country_id'=> 4],
            ['name'=> 'Southland','country_id'=> 4],
            ['name'=> 'Taranaki','country_id'=> 4],
            ['name'=> 'Tasman','country_id'=> 4],
            ['name'=> 'Waikato','country_id'=> 4],
            ['name'=> 'Wellington','country_id'=> 4],
            ['name'=> 'West Coast','country_id'=> 4],

            ['name'=> 'Abu Dhabi','country_id'=> 5],
            ['name'=> 'Ajman','country_id'=> 5],
            ['name'=> 'Dubai','country_id'=> 5],
            ['name'=> 'Ras al-Khaymah','country_id'=> 5],
            ['name'=> 'Sharjah','country_id'=> 5],
            ['name'=> 'Sharjha','country_id'=> 5],
            ['name'=> 'Umm al Qaywayn','country_id'=> 5],
            ['name'=> 'al-Fujayrah','country_id'=> 5],
            ['name'=> 'ash-Shariqah','country_id'=> 5],

            ['name'=> 'Aberdeen','country_id'=> 6],
            ['name'=> 'Aberdeenshire','country_id'=> 6],
            ['name'=> 'Argyll','country_id'=> 6],
            ['name'=> 'Armagh','country_id'=> 6],
            ['name'=> 'Bedfordshire','country_id'=> 6],
            ['name'=> 'Belfast','country_id'=> 6],
            ['name'=> 'Berkshire','country_id'=> 6],
            ['name'=> 'Birmingham','country_id'=> 6],
            ['name'=> 'Brechin','country_id'=> 6],
            ['name'=> 'Bridgnorth','country_id'=> 6],
            ['name'=> 'Bristol','country_id'=> 6],
            ['name'=> 'Buckinghamshire','country_id'=> 6],
            ['name'=> 'Cambridge','country_id'=> 6],
            ['name'=> 'Cambridgeshire','country_id'=> 6],
            ['name'=> 'Channel Islands','country_id'=> 6],
            ['name'=> 'Cheshire','country_id'=> 6],
            ['name'=> 'Cleveland','country_id'=> 6],
            ['name'=> 'Co Fermanagh','country_id'=> 6],
            ['name'=> 'Conwy','country_id'=> 6],
            ['name'=> 'Cornwall','country_id'=> 6],
            ['name'=> 'Coventry','country_id'=> 6],
            ['name'=> 'Craven Arms','country_id'=> 6],
            ['name'=> 'Cumbria','country_id'=> 6],
            ['name'=> 'Denbighshire','country_id'=> 6],
            ['name'=> 'Derby','country_id'=> 6],
            ['name'=> 'Derbyshire','country_id'=> 6],
            ['name'=> 'Devon','country_id'=> 6],
            ['name'=> 'Dial Code Dungannon','country_id'=> 6],
            ['name'=> 'Didcot','country_id'=> 6],
            ['name'=> 'Dorset','country_id'=> 6],
            ['name'=> 'Dunbartonshire','country_id'=> 6],
            ['name'=> 'Durham','country_id'=> 6],
            ['name'=> 'East Dunbartonshire','country_id'=> 6],
            ['name'=> 'East Lothian','country_id'=> 6],
            ['name'=> 'East Midlands','country_id'=> 6],
            ['name'=> 'East Sussex','country_id'=> 6],
            ['name'=> 'East Yorkshire','country_id'=> 6],
            ['name'=> 'England','country_id'=> 6],
            ['name'=> 'Essex','country_id'=> 6],
            ['name'=> 'Fermanagh','country_id'=> 6],
            ['name'=> 'Fife','country_id'=> 6],
            ['name'=> 'Flintshire','country_id'=> 6],
            ['name'=> 'Fulham','country_id'=> 6],
            ['name'=> 'Gainsborough','country_id'=> 6],
            ['name'=> 'Glocestershire','country_id'=> 6],
            ['name'=> 'Gwent','country_id'=> 6],
            ['name'=> 'Hampshire','country_id'=> 6],
            ['name'=> 'Hants','country_id'=> 6],
            ['name'=> 'Herefordshire','country_id'=> 6],
            ['name'=> 'Hertfordshire','country_id'=> 6],
            ['name'=> 'Ireland','country_id'=> 6],
            ['name'=> 'Isle Of Man','country_id'=> 6],
            ['name'=> 'Isle of Wight','country_id'=> 6],
            ['name'=> 'Kenford','country_id'=> 6],
            ['name'=> 'Kent','country_id'=> 6],
            ['name'=> 'Kilmarnock','country_id'=> 6],
            ['name'=> 'Lanarkshire','country_id'=> 6],
            ['name'=> 'Lancashire','country_id'=> 6],
            ['name'=> 'Leicestershire','country_id'=> 6],
            ['name'=> 'Lincolnshire','country_id'=> 6],
            ['name'=> 'Llanymynech','country_id'=> 6],
            ['name'=> 'London','country_id'=> 6],
            ['name'=> 'Ludlow','country_id'=> 6],
            ['name'=> 'Manchester','country_id'=> 6],
            ['name'=> 'Mayfair','country_id'=> 6],
            ['name'=> 'Merseyside','country_id'=> 6],
            ['name'=> 'Mid Glamorgan','country_id'=> 6],
            ['name'=> 'Middlesex','country_id'=> 6],
            ['name'=> 'Mildenhall','country_id'=> 6],
            ['name'=> 'Monmouthshire','country_id'=> 6],
            ['name'=> 'Newton Stewart','country_id'=> 6],
            ['name'=> 'Norfolk','country_id'=> 6],
            ['name'=> 'North Humberside','country_id'=> 6],
            ['name'=> 'North Yorkshire','country_id'=> 6],
            ['name'=> 'Northamptonshire','country_id'=> 6],
            ['name'=> 'Northants','country_id'=> 6],
            ['name'=> 'Northern Ireland','country_id'=> 6],
            ['name'=> 'Northumberland','country_id'=> 6],
            ['name'=> 'Nottinghamshire','country_id'=> 6],
            ['name'=> 'Oxford','country_id'=> 6],
            ['name'=> 'Powys','country_id'=> 6],
            ['name'=> 'Roos-shire','country_id'=> 6],
            ['name'=> 'SUSSEX','country_id'=> 6],
            ['name'=> 'Sark','country_id'=> 6],
            ['name'=> 'Scotland','country_id'=> 6],
            ['name'=> 'Scottish Borders','country_id'=> 6],
            ['name'=> 'Shropshire','country_id'=> 6],
            ['name'=> 'Somerset','country_id'=> 6],
            ['name'=> 'South Glamorgan','country_id'=> 6],
            ['name'=> 'South Wales','country_id'=> 6],
            ['name'=> 'South Yorkshire','country_id'=> 6],
            ['name'=> 'Southwell','country_id'=> 6],
            ['name'=> 'Staffordshire','country_id'=> 6],
            ['name'=> 'Strabane','country_id'=> 6],
            ['name'=> 'Suffolk','country_id'=> 6],
            ['name'=> 'Surrey','country_id'=> 6],
            ['name'=> 'Sussex','country_id'=> 6],
            ['name'=> 'Twickenham','country_id'=> 6],
            ['name'=> 'Tyne and Wear','country_id'=> 6],
            ['name'=> 'Tyrone','country_id'=> 6],
            ['name'=> 'Utah','country_id'=> 6],
            ['name'=> 'Wales','country_id'=> 6],
            ['name'=> 'Warwickshire','country_id'=> 6],
            ['name'=> 'West Lothian','country_id'=> 6],
            ['name'=> 'West Midlands','country_id'=> 6],
            ['name'=> 'West Sussex','country_id'=> 6],
            ['name'=> 'West Yorkshire','country_id'=> 6],
            ['name'=> 'Whissendine','country_id'=> 6],
            ['name'=> 'Wiltshire','country_id'=> 6],
            ['name'=> 'Wokingham','country_id'=> 6],
            ['name'=> 'Worcestershire','country_id'=> 6],
            ['name'=> 'Wrexham','country_id'=> 6],
            ['name'=> 'Wurttemberg','country_id'=> 6],
            ['name'=> 'Yorkshire','country_id'=> 6],
            
            ['name'=> 'Alabama','country_id'=> 7],
            ['name'=> 'Alaska','country_id'=> 7],
            ['name'=> 'Arizona','country_id'=> 7],
            ['name'=> 'Arkansas','country_id'=> 7],
            ['name'=> 'Byram','country_id'=> 7],
            ['name'=> 'California','country_id'=> 7],
            ['name'=> 'Cokato','country_id'=> 7],
            ['name'=> 'Colorado','country_id'=> 7],
            ['name'=> 'Connecticut','country_id'=> 7],
            ['name'=> 'Delaware','country_id'=> 7],
            ['name'=> 'District of Columbia','country_id'=> 7],
            ['name'=> 'Florida','country_id'=> 7],
            ['name'=> 'Georgia','country_id'=> 7],
            ['name'=> 'Hawaii','country_id'=> 7],
            ['name'=> 'Idaho','country_id'=> 7],
            ['name'=> 'Illinois','country_id'=> 7],
            ['name'=> 'Indiana','country_id'=> 7],
            ['name'=> 'Iowa','country_id'=> 7],
            ['name'=> 'Kansas','country_id'=> 7],
            ['name'=> 'Kentucky','country_id'=> 7],
            ['name'=> 'Louisiana','country_id'=> 7],
            ['name'=> 'Lowa','country_id'=> 7],
            ['name'=> 'Maine','country_id'=> 7],
            ['name'=> 'Maryland','country_id'=> 7],
            ['name'=> 'Massachusetts','country_id'=> 7],
            ['name'=> 'Medfield','country_id'=> 7],
            ['name'=> 'Michigan','country_id'=> 7],
            ['name'=> 'Minnesota','country_id'=> 7],
            ['name'=> 'Mississippi','country_id'=> 7],
            ['name'=> 'Missouri','country_id'=> 7],
            ['name'=> 'Montana','country_id'=> 7],
            ['name'=> 'Nebraska','country_id'=> 7],
            ['name'=> 'Nevada','country_id'=> 7],
            ['name'=> 'New Hampshire','country_id'=> 7],
            ['name'=> 'New Jersey','country_id'=> 7],
            ['name'=> 'New Jersy','country_id'=> 7],
            ['name'=> 'New Mexico','country_id'=> 7],
            ['name'=> 'New York','country_id'=> 7],
            ['name'=> 'North Carolina','country_id'=> 7],
            ['name'=> 'North Dakota','country_id'=> 7],
            ['name'=> 'Ohio','country_id'=> 7],
            ['name'=> 'Oklahoma','country_id'=> 7],
            ['name'=> 'Ontario','country_id'=> 7],
            ['name'=> 'Oregon','country_id'=> 7],
            ['name'=> 'Pennsylvania','country_id'=> 7],
            ['name'=> 'Ramey','country_id'=> 7],
            ['name'=> 'Rhode Island','country_id'=> 7],
            ['name'=> 'South Carolina','country_id'=> 7],
            ['name'=> 'South Dakota','country_id'=> 7],
            ['name'=> 'Sublimity','country_id'=> 7],
            ['name'=> 'Tennessee','country_id'=> 7],
            ['name'=> 'Texas','country_id'=> 7],
            ['name'=> 'Trimble','country_id'=> 7],
            ['name'=> 'Utah','country_id'=> 7],
            ['name'=> 'Vermont','country_id'=> 7],
            ['name'=> 'Virginia','country_id'=> 7],
            ['name'=> 'Washington','country_id'=> 7],
            ['name'=> 'West Virginia','country_id'=> 7],
            ['name'=> 'Wisconsin','country_id'=> 7],
            ['name'=> 'Wyoming','country_id'=> 7],
        ];
        foreach ($states as $state) {
            \DB::table('states')->insert(
                [
                    'name' => $state['name'],
                    'country_id' => $state['country_id'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
